[build]
  command = "pip install -r requirements.txt && streamlit run app.py --server.port 8888 --server.enableCORS false --server.enableXsrfProtection false"
  publish = "./"

[build.environment]
  PYTHON_VERSION = "3.11.16"

[[redirects]]
  from = "/*"
  to = "/:splat"
  status = 200
